#!/usr/bin/python3

import argparse
import subprocess

def parseArgs():
    parser = argparse.ArgumentParser()
    parser.add_argument("host", type=str, help="Host/group to deploy to, or 'all' to deploy to all hosts")
    parser.add_argument("--dry", action="store_true", default=False, help="Dry run, don't actually deploy")
    parser.add_argument("--skip-verification", action="store_true", default=False, help="Skip verification of deployment")
    parser.add_argument("--no-save", action="store_true", default=False, help="Don't write changes to startup config on the switch")
    args = parser.parse_args()

    return args

def main():
    args = parseArgs()

    if not args.skip_verification:
        validate_cmd = ["ansible-playbook", "validate.yaml", "--limit", args.host]
        print("Running CMD: {}".format(" ".join(validate_cmd)))
        subprocess.run(validate_cmd)

    run_cmd = ["ansible-playbook", "site.yaml", "--limit", args.host]

    if args.dry:
        run_cmd += ["--check", "--diff"]

    if not args.no_save:
        run_cmd += ["--extra-vars", "\"save_config=true\""]

    print("Running CMD: {}".format(" ".join(run_cmd)))
    subprocess.run(run_cmd)

if __name__ == "__main__":
    main()
